# Generated by Django 4.2.23 on 2025-08-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="username",
            field=models.CharField(
                default="None", help_text="Display name for the player", max_length=50
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="gamesession",
            name="user_id",
            field=models.CharField(
                help_text="Unique identifier for the player", max_length=100
            ),
        ),
    ]
