# Generated by Django 4.2.23 on 2025-08-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_ledger", "0002_gamesession_username_alter_gamesession_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="final_wallet_balance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Player's wallet balance after the game ended",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="total_winnings",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total amount won (0 if bomb hit, stake * multiplier if cashed out)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
