# Generated by Django 4.2.3 on 2025-10-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_ledger", "0004_gameanalytics"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyProfitStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True,
                        help_text="Date for which profit stats are calculated",
                        unique=True,
                    ),
                ),
                (
                    "profit_data",
                    models.JSONField(
                        help_text="Profit percentages by game type, e.g., {'bomb_flip': 20.5, 'quick_cash': 15.3}"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this record was first created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this record was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Profit Stats",
                "verbose_name_plural": "Daily Profit Stats",
                "db_table": "game_ledger_daily_profit_stats",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="daily_profit_date_desc_idx")
                ],
            },
        ),
    ]
